imag = read.csv('../imaginary_data.csv')
imag$start_year = imag$year
imag$end_year = 2015
source('dendrogram.r')
row.names(imag) = imag$author
plot(as.phylo(hclust(daisy(imag, metric='gower'))),type="fan")
d = daisy(imag)
loc = cmdscale(d)
plot(loc[1], loc[2], axes=FALSE, xlab='', ylab='', type='n', asp=1)
library(network)
x = as.network(as.phylo(daisy(imag, metric="gower")))
x = as.network(as.phylo(hclust(daisy(imag, metric="gower"))))
plot(x, vertex.cex=1:4)
plot(x, vertex.cex=1:4, labels=TRUE)
plot(x, vertex.cex=1:4, displaylabels=TRUE)
plot(x, vertex.cex=1:4, displaylabels=TRUE,label.cex=1:4)
plot(x, vertex.cex=1:4, displaylabels=TRUE,label.cex=c(0.3,.0.6,.8,1))
plot(x, vertex.cex=1:4, displaylabels=TRUE,label.cex=0.4)
plot(x, vertex.cex=1:4, displaylabels=TRUE,label.cex=0.6)
plot(x, vertex.cex=1:3, displaylabels=TRUE,label.cex=0.6)
str(x)
plot(x, vertex.cex=1:4, displaylabels=TRUE,label.cex=rep(0.3,1,0.1))
?cex
??cex
?graphics.par
plot(x, vertex.cex=1:4, displaylabels=TRUE,label.cex=c(0.3,1,0.1))
p = as.phylo(hclust(daisy(imag, metric="gower")))
str(p)
p$tip.label
?as.phylo
library(igraph)
plot(as.igraph(p))
plot(p, vertex.cex=1:4, displaylabels=TRUE,label.cex=c(0.3,1,0.1))
plot(as.network(p), vertex.cex=1:4, displaylabels=TRUE,label.cex=c(0.3,1,0.1))
str(p)
n = as.network(p)
str(n)
plot(as.network(p), vertex.cex=1:4, displaylabels=TRUE,label.cex=c(0.3,1,0.4))
plot(as.network(p), vertex.cex=1:4, displaylabels=TRUE,label.cex=c(0.3,1,0.5))
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=c(0.3,1,0.5))
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=c(0.5,1,0.5))
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7)
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7)
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green')
n$val
svg('../figures/network3.svg')
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green')
dev.off()
svg('../figures/network3.svg')
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green')
dev.off()
svg('figures/network3.svg')
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green')
dev.off()
ls()
pwd()
dir()
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE)
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE)
svg('figures/network3.svg')
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE,title = 'clustering of imaginary authors')
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE,main = 'clustering of imaginary authors')
dev.off()
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE,main = 'clustering of imaginary authors', usecurve=TRUE)
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE,main = 'clustering of imaginary authors', usecurve=TRUE, uselen=TRUE)
plot(as.network(p), vertex.cex=1:2, displaylabels=TRUE,label.cex=0.7, vertex.col='green', jitter=TRUE,main = 'clustering of imaginary authors', usecurve=TRUE, uselen=TRUE, interactive=TRUE)
n$mel
n$mel[1]
n
rbinom(n=111)
rbinom(n=111,2)
rbinom(n=111,2.0.5)
rbinom(111,2.0.5)
?rbinom
rbinom(111,0.5)
rbinom(111,prob=0.5)
rbinom(size=111,prob=0.5)
rbinom(n=111,size=111,prob=0.5)
savehistory('network4.r')
