library(timeline)
imag = read.csv('../imaginary_data.csv', stringsAsFactor=FALSE)
imag$start_year = imag$year
imag$end_year = 2016
imag$duration_weighted = log10(imag$citations/(imag$end_year - imag$start_year))

timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='term')
dev.off()
svg('timeline1.svg', width=10, height=7)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='term')
dev.off()
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='term',group.col='domain')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='term',group.col='primary_discipline')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author', group.col='term', event.label='author')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author', group.col='domain', event.label='author')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  event.label='author')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=4)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=10)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=9)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=5)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=2)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=3)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=3, event.spots=4)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=3, event.spots=40)
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=3, event.spots=40,event.group.col='domain')
timeline(imag[-15,], start.col='start_year', end.col='end_year', event.col='author',  group.col='term', event.label.col='author', label.col='author', event.line=TRUE, num.label.steps=30,text.size=3, event.spots=40,event.group.col='domain')
